#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

# image: mcr.microsoft.com/dotnet/sdk:8.0
image: docker:20.10.7

pipelines:
  default:
    - step:
        name: Build Docker Image
        services:
          - docker
        script:
          - apt-get update && apt-get install -y awscli
          - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 131741888359.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com)
          - docker build -t meuclientetesteautomatizado .
    
    - step:
        name: Run Tests
        services:
          - docker
        script:
          - docker tag meuclientetesteautomatizado:latest 131741888359.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/meuclientetesteautomatizado:latest
          - docker push 131741888359.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/meuclientetesteautomatizado:latest
          - docker pull 131741888359.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/meuclientetesteautomatizado:latest
          - docker run --rm 131741888359.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/meuclientetesteautomatizado:latest dotnet test MeuClienteWebTestProject.csproj
